schema_version: 1

context:
  version: 0.20.0

package:
  name: yamlfmt
  version: ${{ version }}

source:
  url: https://github.com/google/yamlfmt/archive/v${{ version }}.tar.gz
  sha256: de6bc4373ba46c520d936dd4b60395868ec17aba338b9fd849594c1f41b6c057

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - yamlfmt --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: An extensible command line tool or library to format yaml files
  homepage: https://github.com/google/yamlfmt
  repository: https://github.com/google/yamlfmt

extra:
  recipe-maintainers:
    - danielnachun
